#!/usr/bin/env bash
# Diagnostic-only SSE adapter. It deliberately has no sender code path.
set -u
_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../lib" 2>/dev/null && pwd)"; . "$_LIB_DIR/notify-policy.sh"; unset _LIB_DIR
LOG_DIR="${AGENT_NOTIFY_ADAPTER_LOG_DIR:-${AGENT_NOTIFY_STATE_DIR:-$HOME/.local/share/polytoken/logs}/notify-adapter}"; LOG="$LOG_DIR/notify.log"; LOCK="$LOG_DIR/adapter.lock"; MAX="${AGENT_NOTIFY_LOG_MAX_BYTES:-8192}"
log(){ mkdir -p "$LOG_DIR" 2>/dev/null || return; chmod 700 "$LOG_DIR" 2>/dev/null || true; printf '%s|%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> "$LOG" 2>/dev/null || true; chmod 600 "$LOG" 2>/dev/null || true; if [ "$(wc -c < "$LOG" 2>/dev/null || echo 0)" -gt "$MAX" ]; then tail -c "$MAX" "$LOG" > "$LOG.tmp" && mv -f "$LOG.tmp" "$LOG"; fi; }
mkdir -p "$LOG_DIR" 2>/dev/null || exit 0
mkdir "$LOCK" 2>/dev/null || { log "decision=would-suppress reason=claim-exists"; exit 0; }; trap 'rmdir "$LOCK" 2>/dev/null || true' EXIT
startup="${1:-${POLYTOKEN_CONFIG_DIR:-$HOME/.config/polytoken}/startup.json}"; port="$(jq -r '.port // empty' "$startup" 2>/dev/null || true)"; cred="$(jq -r '.credential_file_path // empty' "$startup" 2>/dev/null || true)"; sid="$(jq -r '.session_id // empty' "$startup" 2>/dev/null || true)"
[ -n "$port" ] && [ -n "$sid" ] || { log "decision=diagnostic-skip reason=missing-session-or-port"; exit 0; }
clock="${AGENT_NOTIFY_TEST_NOW:-$(date +%s)}"; tolerance=5; maxage=120; base="${AGENT_NOTIFY_ADAPTER_URL:-http://127.0.0.1:$port/events}"; claims="$LOG_DIR/claims"; mkdir -p "$claims"; chmod 700 "$claims" 2>/dev/null || true
process(){ local line="$1" ts id typ trans reason key age; ts="$(printf '%s' "$line" | jq -r '.emitted_at // empty' 2>/dev/null || true)"; id="$(printf '%s' "$line" | jq -r '.event.interrogative_id // .event.prompt_id // .event.goal.id // empty' 2>/dev/null || true)"; typ="$(printf '%s' "$line" | jq -r '.event.type // .event.kind // "unknown"' 2>/dev/null || echo unknown)"; trans="$(printf '%s' "$line" | jq -r '.event.transition // empty' 2>/dev/null || true)"; reason="$(printf '%s' "$line" | jq -r '.event.reason // empty' 2>/dev/null || true)"; [ -n "$id" ] || { log "decision=diagnostic-skip reason=missing-event-id family=$typ"; return; }; ts="$(policy_epoch "$ts" 2>/dev/null)" || { log "decision=diagnostic-skip reason=unparseable-emitted_at family=$typ id=$id"; return; }; case "$(policy_age_decision "$clock" "$ts" 2>/dev/null)" in stale) log "decision=would-suppress reason=stale-processing family=$typ id=$id"; return;; future) log "decision=would-suppress reason=future-emitted_at family=$typ id=$id"; return;; esac; key="$(policy_episode_key "$line")"; if [ "$trans" = cleared ]; then log "decision=diagnostic-keyed reason=cleared-transition family=$typ id=$id"; return; fi; if [ "$typ" = turn_cancelled ] || [ "$typ" = cancellation ] || [ "$reason" = user_cancelled ]; then log "decision=would-suppress reason=shutdown-evidence-unverified family=$typ id=$id"; return; fi; policy_claim "$LOG_DIR" "$key" || { log "decision=would-suppress reason=claim-loser family=$typ id=$id"; return; }; log "decision=would-send reason=diagnostic-only family=$typ id=$id"; }
[ -f "$cred" ] && bearer="$(jq -r '.token // .credential // empty' "$cred" 2>/dev/null || true)" || bearer=""; args=(-sS -N --max-time 10); [ -n "$bearer" ] && args+=(-H "Authorization: Bearer $bearer"); curl "${args[@]}" "$base" 2>/dev/null | while IFS= read -r line; do case "$line" in data:*) process "${line#data: }";; esac; done
