#!/usr/bin/env bash
# One-time sweep for debris left by crashed polytoken container launches.
#
# A crashed run.sh can leave two kinds of debris in a repo's .polytoken/:
#   - a `.container-config.*/config.yaml` backup dir holding the pristine
#     project config that was never moved back (the crash window — the backup
#     may be the only copy), often next to the launcher's AUTO-GENERATED
#     live config;
#   - only an AUTO-GENERATED config.yaml (its own header says "safe to
#     delete") when no project config existed at launch.
# Stale AUTO-GENERATED configs force bypass_plus over the intended global
# Autonomous config for ordinary host sessions, so they must not survive.
#
# Run this ONCE on the host, AFTER the merge fix in polytoken-container/run.sh
# has landed, and never while a polytoken-dev container is live: a running
# launcher's backup dir is its pending restore source, and touching it would
# break the EXIT trap's mv. The guard below aborts if podman reports any live
# polytoken-dev container (a repo's debris that belongs to a live session —
# e.g. claude-config's — clears itself when that container exits). Known
# blind spots: symlinked .polytoken dirs are not visited (find -type d does
# not match symlinks), and a container launched under a custom POLY_IMAGE
# name is not detected — stop containers or verify manually first if you use
# either.
#
# Scope: every .polytoken dir within the workspace root at depth <= 3.
#   - backup config + (missing OR AUTO-GENERATED live config)
#       -> restore the backup over the live path, remove the emptied backup dir
#   - AUTO-GENERATED live config, no backup -> delete the live config
#   - anything else (a real project config, no debris) -> left untouched
# Every restored/removed/skipped path is printed. Re-running is a no-op.
# A failed restore/remove skips that repo with a message instead of aborting
# the sweep; whatever was already done stays done.
#
# POLY_SWEEP_WS_ROOT overrides the scanned root (used by the sweep's own
# sandbox tests; leave unset on the host).

set -euo pipefail

WS_ROOT="${POLY_SWEEP_WS_ROOT:-$HOME/workspace}"
if [[ ! -d "$WS_ROOT" ]]; then
  echo "sweep: workspace root not found: $WS_ROOT" >&2
  exit 1
fi

# Guard: never run against a workspace with a live polytoken-dev container.
# Matched by image-name prefix rather than a single ancestor filter, since
# podman's ancestor=polytoken-dev misses tag overrides like polytoken-dev:wip
# (run.sh supports those via POLY_TAG).
if ! command -v podman >/dev/null 2>&1; then
  echo "sweep: podman not found — cannot verify that no polytoken-dev container is live; run this on the host." >&2
  exit 1
fi
if ! live_images="$(podman ps --format '{{.Image}}')"; then
  echo "sweep: cannot query podman for live polytoken-dev containers — aborting." >&2
  exit 1
fi
if grep -q '^polytoken-dev' <<<"$live_images"; then
  echo "sweep: polytoken-dev container(s) live — aborting (a running launcher's backup dir is its pending restore source)." >&2
  exit 1
fi

restored=0
removed=0
skipped=0

first_line_is_autogenerated() {  # $1 = candidate config file
  local first=""
  read -r first < "$1" 2>/dev/null || true
  [[ "$first" == *AUTO-GENERATED* ]]
}

# A launcher backup dir holds exactly the moved-aside config.yaml (plus a
# transient merged.yaml when a crash interrupted generation). Anything else
# is a same-named stranger dir — not ours to restore from.
backup_dir_is_launcher_shaped() {
  [[ -f "$1/config.yaml" ]] || return 1
  local strangers
  strangers="$(find "$1" -mindepth 1 -maxdepth 1 ! -name config.yaml ! -name merged.yaml 2>/dev/null | wc -l)" || true
  [[ "$strangers" -eq 0 ]]
}

while IFS= read -r -d '' pt; do
  repo="${pt%/.polytoken}"
  live_cfg="$pt/config.yaml"

  backup_dirs=()
  for b in "$pt"/.container-config.*/; do
    if [[ -d "$b" ]] && backup_dir_is_launcher_shaped "$b"; then
      backup_dirs+=("$b")
    elif [[ -d "$b" ]]; then
      echo "SKIP    $repo: $b is not a launcher backup dir (unexpected contents) — inspect manually"
      skipped=$((skipped + 1))
    fi
  done

  if (( ${#backup_dirs[@]} > 1 )); then
    echo "SKIP    $repo: multiple .container-config backup dirs — resolve manually"
    skipped=$((skipped + 1))
  elif (( ${#backup_dirs[@]} == 1 )); then
    backup="${backup_dirs[0]}"
    if [[ ! -e "$live_cfg" ]] || first_line_is_autogenerated "$live_cfg"; then
      if ! mv "$backup/config.yaml" "$live_cfg"; then
        echo "SKIP    $repo: restore from $backup failed (unwritable target?) — resolve manually"
        skipped=$((skipped + 1))
        continue
      fi
      if ! rmdir "$backup" 2>/dev/null; then
        # A crash-state backup may still hold the transient merged.yaml draft
        # (launcher-generated by shape validation above) — clear it, then retry.
        if [[ -f "$backup/merged.yaml" ]]; then
          rm -f "$backup/merged.yaml" 2>/dev/null || true
        fi
        if ! rmdir "$backup" 2>/dev/null; then
          echo "NOTE    $repo: backup dir not empty after restore, left in place: $backup"
        fi
      fi
      echo "RESTORE $repo: project config recovered from $backup"
      restored=$((restored + 1))
    else
      echo "SKIP    $repo: backup dir present but live config is not launcher debris (real project config or other file) — inspect manually: $backup"
      skipped=$((skipped + 1))
    fi
  elif [[ -e "$live_cfg" ]] && first_line_is_autogenerated "$live_cfg"; then
    if rm -f "$live_cfg"; then
      echo "REMOVE  $repo: stale AUTO-GENERATED config (no backup; its header says safe to delete)"
      removed=$((removed + 1))
    else
      echo "SKIP    $repo: could not remove stale AUTO-GENERATED config — resolve manually"
      skipped=$((skipped + 1))
    fi
  fi
  # Anything else: a real project config with no debris — untouched.
done < <(find "$WS_ROOT" -maxdepth 3 -type d -name .polytoken -print0)

echo "sweep done: $restored restored, $removed removed, $skipped skipped"
